### PR TITLE
The app

### PR DESCRIPTION
**Pull request by woook**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pindel/1)

### CODE REVIEW

**Comment by mattgarner** [comment]
Review on hold, awaiting additional commits

**Review by woook — COMMENTED** [review]
Additional commit is done.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pindel/1#-:-MT6_CvU5AC_u7ysUl-y:b-ef83bp)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pindel/1)* status: all files reviewed, 2 unresolved discussions (waiting on @woook)

___
*[Readme.md, line 3 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pindel/1#-MT565Ur1OwNy9Eu7-1x:-MT565Ur1OwNy9Eu7-1y:b-h48ft1) ([raw file](https://github.com/eastgenomics/eggd_pindel/blob/c512559f6b1dddf4b9516c1287e40d5b469b27f2/Readme.md#L3)):*
> ```
> copy of an applet
> ```
Might be useful to include a reference to the original object
___
*[Readme.md, line 19 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pindel/1#-MT6sKYw8WovOscGaVn9:-MT6sKYw8WovOscGaVnA:b-ogw5t9) ([raw file](https://github.com/eastgenomics/eggd_pindel/blob/c512559f6b1dddf4b9516c1287e40d5b469b27f2/Readme.md#L19)):*
> ```
> mappingsand
> ```
mappings and

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pindel/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @woook)

___
*[Readme.md, line 3 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pindel/1#-MT565Ur1OwNy9Eu7-1x:-MT6v0g-7g8zyClOWCT8:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_pindel/blob/c512559f6b1dddf4b9516c1287e40d5b469b27f2/Readme.md#L3)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> copy of an applet
> ```
Might be useful to include a reference to the original object
</blockquote></details>

Done
___
*[Readme.md, line 19 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pindel/1#-MT6sKYw8WovOscGaVn9:-MT6v36C2Ke3NE1LhFlZ:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_pindel/blob/c512559f6b1dddf4b9516c1287e40d5b469b27f2/Readme.md#L19)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> mappingsand
> ```
mappings and
</blockquote></details>

Done

**Comment by woook** [comment]
___
*[Readme.md, line 3 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pindel/1#-MT565Ur1OwNy9Eu7-1x:-MT6v5_D8GTgjumI4KEk:b-gr0okz) ([raw file](https://github.com/eastgenomics/eggd_pindel/blob/c512559f6b1dddf4b9516c1287e40d5b469b27f2/Readme.md#L3)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> copy of an applet
> ```
Might be useful to include a reference to the original object
</blockquote></details>

References added

**Pull request merged**
